// Sample product categories with icons
export const sampleCategories = [
  {
    id: "electronics",
    name: "Electronics",
    image: "/placeholder.svg?height=200&width=200&text=Electronics",
    icon: "Smartphone",
    productCount: 42,
  },
  {
    id: "fashion",
    name: "Fashion",
    image: "/placeholder.svg?height=200&width=200&text=Fashion",
    icon: "Shirt",
    productCount: 56,
  },
  {
    id: "home",
    name: "Home & Kitchen",
    image: "/placeholder.svg?height=200&width=200&text=Home",
    icon: "Home",
    productCount: 38,
  },
  {
    id: "beauty",
    name: "Beauty & Personal Care",
    image: "/placeholder.svg?height=200&width=200&text=Beauty",
    icon: "Sparkles",
    productCount: 29,
  },
  {
    id: "sports",
    name: "Sports & Outdoors",
    image: "/placeholder.svg?height=200&width=200&text=Sports",
    icon: "Dumbbell",
    productCount: 24,
  },
  {
    id: "books",
    name: "Books & Stationery",
    image: "/placeholder.svg?height=200&width=200&text=Books",
    icon: "BookOpen",
    productCount: 31,
  },
]

// Sample featured products
export const sampleFeaturedProducts = [
  {
    id: "prod-1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 1299.99,
    image: "/images/headphones.png",
    stock: 15,
    discount: 10,
    category: "electronics",
    featured: true,
  },
  {
    id: "prod-2",
    name: "Stylish Smartwatch",
    description: "Modern smartwatch with health tracking features",
    price: 899.99,
    image: "/images/smartwatch.png",
    stock: 8,
    discount: 0,
    category: "electronics",
    featured: true,
  },
  {
    id: "prod-3",
    name: "Designer Sunglasses",
    description: "Trendy sunglasses with UV protection",
    price: 499.99,
    image: "/images/sunglasses.png",
    stock: 20,
    discount: 15,
    category: "fashion",
    featured: true,
  },
  {
    id: "prod-4",
    name: "Organic Skincare Set",
    description: "Natural and organic skincare products",
    price: 799.99,
    image: "/images/skincare.png",
    stock: 12,
    discount: 5,
    category: "beauty",
    featured: true,
  },
]

// Sample recommended products
export const sampleRecommendedProducts = [
  {
    id: "prod-5",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof speaker with amazing sound quality",
    price: 599.99,
    image: "/images/speaker.png",
    stock: 18,
    discount: 0,
    category: "electronics",
  },
  {
    id: "prod-6",
    name: "Fitness Tracker",
    description: "Track your activities and monitor your health",
    price: 399.99,
    image: "/images/fitness-tracker.png",
    stock: 25,
    discount: 10,
    category: "electronics",
  },
  {
    id: "prod-7",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots",
    price: 249.99,
    image: "/images/wallet.png",
    stock: 30,
    discount: 0,
    category: "fashion",
  },
  {
    id: "prod-8",
    name: "Stainless Steel Water Bottle",
    description: "Keep your drinks hot or cold for hours",
    price: 149.99,
    image: "/images/water-bottle.png",
    stock: 40,
    discount: 5,
    category: "home",
  },
]
